---
layout: home
title: "Priyadarshini Maddela | Business Intelligence Portfolio"
subtitle: "Business Intelligence | Data Analytics | Business Analysis"
---

<div style="background-color:#222; color:white; padding: 40px; text-align: center;">

# 👋 Hi, I'm Priya

### MSIT Graduate Student at Clark University

<img src="/assets/images/your_image.jpg" alt="Priyadarshini Maddela" width="300" style="border-radius: 10px; margin-top: 20px;"/>

</div>

---

<div style="background-color:#e3edf0; padding: 20px; border-radius: 10px;">

## 📖 About Me

Hey! I'm Priyadarshini Maddela, currently pursuing a Master of Science in Information Technology at Clark University in Massachusetts.

Experienced **Business Analyst** with 4 years of experience in **business process improvement**, **stakeholder collaboration**, and **data-driven decision-making**.  
Skilled in **requirements gathering**, **reporting**, **BI tools**, and **project management**.  
Proven ability to analyze complex datasets, optimize workflows, and enhance operational efficiency.

Proficient in **Tableau, Power BI, Google Analytics, SQL, and Jira** to provide actionable insights. Seeking a challenging Business Analyst role to apply analytical and strategic thinking to optimize business processes.

*Let's connect and explore the endless possibilities in tech!*

</div>

---

<div align="center">

## 📌 Quick Info

**MSIT '25 | Clarkie | Ex-Infoscion | B.Tech**

My technical skillset includes **C, SQL, R, Python**, and data visualization tools like **Excel, Splunk, Tableau & Power BI**.  
Strong skills in **problem-solving, optimization, presentation, communication, and leadership**.

</div>

---

<div align="center">

<h2>📬 Connect with Me</h2>

<a href="mailto:maddelapriyadarshini@gmail.com"><img src="/assets/images/outlook.jpg" width="50" alt="Email" style="margin: 5px;"></a>
<a href="https://www.linkedin.com/in/pmaddela/"><img src="/assets/images/linkedin.jpg" width="50" alt="LinkedIn" style="margin: 5px;"></a>
<a href="https://github.com/PriyadarshiniMaddela"><img src="/assets/images/github.jpg" width="50" alt="GitHub" style="margin: 5px;"></a>
<a href="#"><img src="/assets/images/wtsapp.jpg" width="50" alt="WhatsApp" style="margin: 5px;"></a>

<p><strong>Contact me at PMaddela@clarku.edu</strong></p>

</div>


