# Welcome to Jekyll!

minimal_mistakes_skin: "default"

# -------------------------------------
# Site Settings
# -------------------------------------

locale: "en-US"
title: "Priyadarshini Maddela | BI & Data Analytics Portfolio"
title_separator: "-"
description: "Showcasing Business Intelligence, Data Visualization, and Business Analysis Projects"
name: "Priyadarshini Maddela"
url: "https://priyadarshnimaddela.github.io"
baseurl: ""

# -------------------------------------
# Author Settings
# -------------------------------------

author:
  name: "Priyadarshini Maddela"
  avatar: "/assets/images/profile.jpg"
  bio: "Business Intelligence | Data Analysis | Business Analysis"
  location: "Worcester, MA"
  email: "maddelapriyadarshini@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:maddelapriyadarshini@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pmaddela/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PriyadarshiniMaddela"

# -------------------------------------
# Footer Links
# -------------------------------------

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pmaddela/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PriyadarshiniMaddela"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:maddelapriyadarshini@gmail.com"
    - label: "WhatsApp"
      icon: "fab fa-fw fa-whatsapp"
      url: "#"   # <-- Replace # with your WhatsApp link if you want -> Example: https://wa.me/15551234567

# -------------------------------------
# Theme and Build Settings
# -------------------------------------

remote_theme: "mmistakes/minimal-mistakes"

include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone:

paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      css: "/assets/css/custom.css"
